name: recipt_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.0







dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5           # Quản lý trạng thái
  hive: ^2.0.4          # Lưu trữ cục bộ
  hive_flutter: ^1.1.0  # Tích hợp Hive với Flutter
  dio: ^4.0.6           # Gọi API
  logger: ^2.0.2 # hoặc phiên bản mới nhất
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
